### ISSUE TITLE
20230926 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [handonghoo/C202309#1]
handonghoo 한동호 2023-09-12 16:42:19 2023-09-20 15:58:08 no covered commit

수업 시간에 등록된 커밋이 없습니다.

(CPP 저장소에 올린 것 같습니다. 확인 후 재 업로드 해주세요)

**Comment by handonghoo** [comment]
안녕하십니까 교수님, 교수님의 기초언어수업 3가지를 모두 듣고 있는 영어영문학과 학생 한동호입니다.


handonghoo 한동호* 2023-09-12 16:42:19 2023-09-20 15:58:08* no covered commit

수업 시간에 등록된 커밋이 없습니다.

(CPP 저장소에 올린 것 같습니다. 확인 후 재 업로드 해주세요)

다음과 같은 메일을 받고선 일단 최근 수업시간에 했던 실습이 잘못 커밋되었음을 알게 되었습니다.
해당 이슈에대해 커밋메세지를 C와C++  각각의 저장소에 "Issue checked" , "Issue solved" 로 달고 저장소를
수정했습니다.
다만,최근에 커밋한 이슈와 무관하게 * 2023-09-12 16:42:19 2023-09-20 15:58:08* 이 시간대에 커밋이
안되었다는 메세지를 받았는데 어떤 부분을 커밋을 안했는지 정확히 잘 모르겠습니다.
최근 사례를 제외하고, 커밋 메시지를 시간에 맟춰 정상적으로 발송하였음을 확인하였고, 혹시 제가 다른 부분에서 실수를 한 것이 있는지 확인부탁드립니다. 


2023년 9월 26일 (화) 오후 4:13, MisooKim2 ***@***.***>님이 작성:

**Comment by MisooKim2** [comment]
한동호 학생 안녕하세요.

출력된 해당 일시는 한동호 학생이 해당 저장소에서 가장 최근에 커밋한 일시를 의미합니다.
즉, 해당 일시에 커밋이 없다는 메시지는 아니니 안심하셔도 됩니다.
메시지가 오해의 소지가 있어 보이니 차후 피드백에서는 수정토록 하겠습니다.
또한 한동호 학생 저장소를 체크한 결과 현재는 아무 문제가 없는 것 확인하였습니다.

그리고 이슈 해결 후, 깃헙 이슈에서 closed issue를 클릭하여 이슈가 해결되었음을 체크해주세요.

수고하셨습니다.

- 김미수 드림 -
