### ISSUE TITLE
20231004 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [handonghoo/C202309#2]
워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 5]
         - 이유: main의 반환값은 int 여야 합니다
         - 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.
    - Warning: format specifies type 'int' but the argument has type 'long' [line 6]
    - Warning: format specifies type 'int' but the argument has type 'long' [line 7]
    - Warning: format specifies type 'int' but the argument has type 'long' [line 8]
        - 이유: 서식지정자 %d는 int 데이터를 위한 지정자입니다
        - 해결: %d를 %ld로 바꾸세요
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]
         - 이유: main의 반환값은 int 여야 합니다
         - 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.

**Comment by MisooKim2** [comment]
제가 수업시간에 void main() 함수에 대해 알려드렸었는데,
최근 컴파일러들이 해당 코드를 지양하는 추세라고 합니다.
하여 워닝 메세지에 추가되었으니 수정부탁드립니다.
관련하여 수업시간에 추가 공지하도록 하겠습니다.

**Comment by handonghoo** [comment]
현시간부로 해당사항 체크 완료하였고 수정하였습니다.
커밋메시지는 " issue solved 1007 " 입니다. 

- 한동호 학생 올림
