### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [handonghoo/C202309#3]
### 없는 파일
- challenge/week6/studentGrade.c
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/zeroTwoIf
    - Warning: using the result of an assignment as a condition without parentheses [line 9]
    - Warning: using the result of an assignment as a condition without parentheses [line 11]
    - Warning: using the result of an assignment as a condition without parentheses [line 13]
       -  "=" 은 변수에 값을 할당하는 연산을 합니다. 조건문에서 A와 B가 같다를 조건으로 주기 위해서는 "==" 을 입력해야 합니다. 조건문의 관계연산자를 수정해주세요.

**Comment by handonghoo** [comment]
420dc590671b70cac812b32d43ba539b4f167e92

**Comment by handonghoo** [comment]
인지 및 수정 완료하였습니다.
